name: prometheus_remote_write
version: 0
status: published

providers:
  - name: prometheus-k8s
    url: https://www.github.com/canonical/prometheus-k8s

requirers:
  - name: grafana-agent-k8s
    url: https://www.github.com/canonical/grafana-agent-k8s

owners:
  - mmkay
  - Abuelodelanada
  - simskij
  - dstathis
  - PietroPasotti
  - michaeldmitry
  - lucabello
  - ca-scribner
  - IbraAoad
  - sed-i
  - MichaelThamm
